# Tensorflow 

## 基于 docker 的 GPU 环境搭建 

```bash
# 下载 NVIDIA 驱动
# sudo bash NVIDIA-Linux-x86_64-410.104.run

# 安装 docker-ce
# 删除系统中已经安装的 Docker 相关系统
sudo apt-get remove docker docker-engine docker-ce docker.io

# 更新系统资源
sudo apt-get update

# 安装 Https 插件， 以便可以访问 HTTPS 资源
sudo apt-get -y install apt-transport-https ca-certifications curl software-properties-common

# 获取 Docker-ce 的资源密钥
curl -fsSL http://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | sudo apt-key add -

# 将 docker-ce 的资源添加到 apt 库中
sudo add-apt-repository "deb[arch=amd64]http://mirrors.aliyun.com/ docker-ce/linux/ubuntu $(lsb_release -cs) stable"

# 更新系统资源
sudo apt-get update

sudo apt-get -y install docker-ce

sudo apt-get -y purge nvidia-docker

curl -s -L http://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -

distribution=$(. /etc/os-release; echo $ID$VERSION_ID)

curl -s -L http://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

sudo apt-get update

sudo apt-get -y install nvidia-docker2

reboot

docker run --runtime=nvidia -it -rm tensorflow/tensorflow:latest-gpu \
python -c "import tensorflow as tf;
print(tf.reduce_sum(tf.random_normal([1000,1000])))
"

```

## Tensorflow 2.0 基础知识

### Tensorflow 2.0 AutoGraph 简介

tf.funtion 装饰器

### Tensorflow 2.0 低阶 API 基础编程

1. tf.constant

In [1]:
import tensorflow as tf

a = tf.constant(7)

a

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [2]:
a.numpy()

7

2. tf.Variable

In [3]:
import tensorflow as tf

a1 = 7

a2 = tf.Variable(7)

a3 = tf.Variable([0, 1, 2])

a1, a2, a3

(7,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>,
 <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 1, 2], dtype=int32)>)

3. tf.reshape

In [5]:
import tensorflow as tf

a = tf.Variable([[0, 1, 2], [3, 4, 5]])

print(a.shape)

a1 = tf.reshape(a, [3, 2])
print(a1.shape)

(2, 3)
(3, 2)


4. tf.math.reduce_mean

In [6]:
import tensorflow as tf

a = tf.constant([1,2,3,4,5,6,7.])
print(a.dtype)
print(tf.math.reduce_mean(a))

b = tf.constant([[1,2,1], [5,2,10]])
print(b.dtype)
print(tf.math.reduce_mean(b))


<dtype: 'float32'>
tf.Tensor(4.0, shape=(), dtype=float32)
<dtype: 'int32'>
tf.Tensor(3, shape=(), dtype=int32)


5. tf.random.normal

正态分布

In [7]:
import tensorflow as tf

a = tf.random.normal(shape=[2, 3], mean=2)

print(a.numpy())

[[2.864081   1.3214331  1.7592307 ]
 [2.5351386  0.04394543 1.2617177 ]]


6. tf.random.uniform

均匀分布

In [8]:
import tensorflow as tf

a = tf.random.uniform(shape=[2, 3], minval=1, maxval=10, seed=8, dtype=tf.int32)

print(a.numpy())

[[4 9 9]
 [6 4 9]]


7. tf.transpose

矩阵转置

In [9]:
import tensorflow as tf

x = tf.constant([ [[1, 2, 3], [4, 5, 6]], [[7,8,9], [10,11,12]] ])

a = tf.transpose(x, perm=[0,2,1])

print(a.numpy())

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


8. tf.math.argmax

数组内最大值索引

In [11]:
import tensorflow as tf

a = tf.constant([1,2,3,4,5])

x = tf.math.argmax(a)

print(x.numpy())

4


9. tf.expand_dims

扩展纬度

In [12]:
import tensorflow as tf

a = tf.constant([[1],[2],[3]])
print(x.shape)
b = tf.expand_dims(a, 0)

print(b)

()
tf.Tensor(
[[[1]
  [2]
  [3]]], shape=(1, 3, 1), dtype=int32)


10. tf.concat

In [13]:
import tensorflow as tf

a1 = tf.constant([[2, 3, 4], [4, 5, 6], [2, 3, 4]])
a2 = tf.constant([[1, 2, 2], [6, 7, 9], [2, 3, 2]])

b = tf.concat([a1, a2], axis=0)

print(b.numpy())

[[2 3 4]
 [4 5 6]
 [2 3 4]
 [1 2 2]
 [6 7 9]
 [2 3 2]]


11. tf.bitcast

数据类型转换

In [15]:
import tensorflow as tf

a = tf.constant(32.0)

b = tf.bitcast(a, type=tf.int32)

print(a.dtype)

print(b.dtype)

<dtype: 'float32'>
<dtype: 'int32'>
